name: Tests
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - main
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Anchor
        uses: metadaoproject/setup-anchor@v3.4
      - name: Test
        run: anchor test
